### ISSUE TITLE
ncmt “Read <unnamed> panicked at 'error thread task: reqwest::Error"

### ISSUE THREAD

**Issue by michaelfyc** [betta-cyber/netease-music-tui#13]
**Environment**: MacOS Catalina 10.15.3
**Souce**: From release binay
**Description**: ncmt logged in successfully. I can see all of my playlists. However, when I tried  to play one of the songs, an error jumped up:
```
Read <unnamed> panicked at 'error thread task: reqwest::Error{kind:Request, url: http://m7.music.126.net/...", source: hyper::Error(Connect, "socks connect error:Proxy server unreachable")}', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
``` 
What's even worst is that when the error jumped out, the whole session froze. I'll have to force-close it. 
I'm completely new to Rust.. Is there any solution to this?

**Comment by betta-cyber** [comment]
Sorry about that. it's the same problem in #9 
so I will publish a new release to fix it or you can build the latest code by yourself
