### ISSUE TITLE
Cannot play flac audio

### ISSUE THREAD

**Issue by YXL76** [betta-cyber/netease-music-tui#19]
When playing flac audio, this program will exit

**Comment by betta-cyber** [comment]
flac audio doesn't support now. flac decoder will be supported as soon as possible.

**Comment by YangtseSu** [comment]
上传到云盘的音乐文件是flac格式的，因为没有对应的mp3格式，所以总是会导致ncmt异常退出。

**Comment by betta-cyber** [comment]
fix in the  latest version @YXL76 @YangtseSu 

[8068570](https://github.com/betta-cyber/netease-music-tui/commit/80685703bcc2197ed20293978751d18232bc49d1)
