### ISSUE TITLE
Some times Error,throw stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by readmagic** [betta-cyber/netease-music-tui#22]
Some times run the application ,Throw 《stream did not contain valid UTF-8》, I'm new to Rust。But I found the problem。
netease some times will respond the "content-encoding:br" in header.So the reqwest crash。
bug fix in api.rs
    headers.insert(ACCEPT_ENCODING, "gzip,deflate,br".parse().unwrap());
change to
    headers.insert(ACCEPT_ENCODING, "gzip,deflate".parse().unwrap());

then solved。

**Comment by betta-cyber** [comment]
thank you !!
