### ISSUE TITLE
Some times,search the songs will crash.

### ISSUE THREAD

**Issue by readmagic** [betta-cyber/netease-music-tui#23]
There are none errors  throw out.Just the application exit.I don't know how to debug in rust.
Is there anyone like me?

**Comment by betta-cyber** [comment]
If you exit without some errors. maybe you could turn on the debug mode and search log for the errors. add "debug = True" in Settings.toml

**Comment by readmagic** [comment]
Thank you very much.

**Comment by readmagic** [comment]
It's no crash later。
