### ISSUE TITLE
v0.1.3 Ncmt play music without sound on Linux

### ISSUE THREAD

**Issue by yjun123** [betta-cyber/netease-music-tui#24]
I use precompile binary file, download from github release, execute it,
select any song from my playlist, seem ncmt is playing the song, but without any sound

![image](https://user-images.githubusercontent.com/24363384/109417818-25efe700-7a00-11eb-80e6-14adee203413.png)
 
environment:
OS: Arch Linux 5.10.19-1-lts
pulseaudio: 14.2
pulseaudio-alsa: 1.2.2

**Comment by ayamir** [comment]
This problem also occurred when I built from source on gentoo linux.
pulseaudio: 13.0
kernel: 5.10.0-gentoo

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/109729901-93179e00-7bf3-11eb-98b9-ce2d1a14a842.png)
I doubt that this is the reason.

**Comment by tanhaipeng** [comment]
same problems(No sound) on mac

**Comment by wgxh** [comment]
me too

**Comment by VergeDX** [comment]
Same issues here, NixOS 21.05.

**Comment by LordCasser** [comment]
Same issues, Ubuntu20.04

**Comment by betta-cyber** [comment]
#27 fix issue
