### ISSUE TITLE
[Feature Request] remove gstreamer player dependencies

### ISSUE THREAD

**Issue by betta-cyber** [betta-cyber/netease-music-tui#5]
gstreamer is too complex for this music player. so we need remove it.

**Comment by betta-cyber** [comment]
#6

**Comment by betta-cyber** [comment]
#6 and seek need to be implemented

**Comment by ttys3** [comment]
@betta-cyber  maybe you can use [mpg123](https://www.mpg123.de/) to play music like this project: https://github.com/darknessomi/musicbox ?
