### ISSUE TITLE
change project name to netease-cloud-music-tui

### ISSUE THREAD

**Issue by ttys3** [betta-cyber/netease-music-tui#8]
since the bin name is `ncmt` , which is short for `netease-cloud-music-tui`

maybe `netease-cloud-music-tui` is better ?

**Comment by betta-cyber** [comment]
ok, you can change it by yourself. which it's define in Cargo.toml bin path.
maybe `netease-cloud-music-tui` it's more clear but it's too long for me 😂

**Comment by ttys3** [comment]
:smiley_cat:

**Comment by ttys3** [comment]
nerver mind. just a suggestion
